# Generated by Django 5.0.6 on 2026-07-06 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='category',
            field=models.CharField(default='Currency', help_text='e.g. Currency, Pass, Bundle', max_length=80),
        ),
    ]
